function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu(TGI.APP_NAME)
    .addItem('Install / repair workbook', 'installTryHardGuestIntelligence')
    .addSeparator()
    .addItem('Create / repair all five forms', 'createTryHardForms')
    .addItem('Install form-submit triggers', 'installTryHardFormTriggers')
    .addItem('Show form links', 'showTryHardFormLinks')
    .addSeparator()
    .addItem('Add sample guest', 'addSampleGuest')
    .addItem('Validate installation', 'validateTryHardInstallation')
    .addToUi();
}

function installTryHardGuestIntelligence() {
  var result = TGI.WorkbookInstaller.install();
  SpreadsheetApp.getUi().alert(
    TGI.APP_NAME,
    'Installation complete.\nSchema version: ' + result.schemaVersion,
    SpreadsheetApp.getUi().ButtonSet.OK
  );
  return result;
}

function createTryHardForms() {
  TGI.WorkbookInstaller.install();
  var forms = TGI.FormBuilder.createAll();
  SpreadsheetApp.getUi().alert(
    TGI.APP_NAME,
    forms.length + ' forms are ready. Install the form-submit triggers next.',
    SpreadsheetApp.getUi().ButtonSet.OK
  );
  return forms;
}

function installTryHardFormTriggers() {
  var triggers = TGI.TriggerManager.installFormSubmitTriggers();
  SpreadsheetApp.getUi().alert(
    TGI.APP_NAME,
    triggers.length + ' form-submit triggers installed.',
    SpreadsheetApp.getUi().ButtonSet.OK
  );
  return triggers;
}

function showTryHardFormLinks() {
  var registry = TGI.FormBuilder.getRegistry();
  var lines = Object.keys(registry).sort().map(function (key) {
    return registry[key].title + '\nPublic: ' + registry[key].publishedUrl + '\nEdit: ' + registry[key].editUrl;
  });
  SpreadsheetApp.getUi().alert(
    TGI.APP_NAME,
    lines.length ? lines.join('\n\n') : 'No forms are registered. Create the forms first.',
    SpreadsheetApp.getUi().ButtonSet.OK
  );
  return registry;
}

function validateTryHardInstallation() {
  var spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  var missing = TGI.Schema.names().filter(function (name) {
    return !spreadsheet.getSheetByName(name);
  });
  if (missing.length) throw new Error('Missing sheets: ' + missing.join(', '));

  var registry = TGI.FormBuilder.getRegistry();
  var triggerCount = TGI.TriggerManager.listManagedTriggers().length;
  var message = 'Workbook schema is valid.\nRegistered forms: ' + Object.keys(registry).length +
    '\nManaged form triggers: ' + triggerCount;
  SpreadsheetApp.getUi().alert(TGI.APP_NAME, message, SpreadsheetApp.getUi().ButtonSet.OK);
  return { valid: true, formCount: Object.keys(registry).length, triggerCount: triggerCount };
}

function addSampleGuest() {
  var guest = TGI.GuestRepository.save({
    first_name: 'Sample',
    last_name: 'Guest',
    email: 'sample+' + new Date().getTime() + '@example.com',
    country: 'Japan',
    language: 'ja',
    source: TGI.Enums.SOURCE.SYSTEM,
    notes: 'Generated by the installation smoke test.'
  });
  SpreadsheetApp.getUi().alert(
    TGI.APP_NAME,
    'Created guest: ' + guest.guest_id,
    SpreadsheetApp.getUi().ButtonSet.OK
  );
  return guest;
}
