function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu(TGI.APP_NAME)
    .addItem('Install / repair workbook', 'installTryHardGuestIntelligence')
    .addItem('Add sample guest', 'addSampleGuest')
    .addItem('Validate installation', 'validateTryHardInstallation')
    .addToUi();
}

function installTryHardGuestIntelligence() {
  var result = TGI.WorkbookInstaller.install();
  SpreadsheetApp.getUi().alert(
    TGI.APP_NAME,
    'Installation complete.\nSchema version: ' + result.schemaVersion,
    SpreadsheetApp.getUi().ButtonSet.OK
  );
  return result;
}

function validateTryHardInstallation() {
  var spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  var missing = TGI.Schema.names().filter(function (name) {
    return !spreadsheet.getSheetByName(name);
  });

  if (missing.length) {
    throw new Error('Missing sheets: ' + missing.join(', '));
  }

  SpreadsheetApp.getUi().alert(
    TGI.APP_NAME,
    'Installation is valid.',
    SpreadsheetApp.getUi().ButtonSet.OK
  );
  return true;
}

function addSampleGuest() {
  var guest = TGI.GuestRepository.save({
    first_name: 'Sample',
    last_name: 'Guest',
    email: 'sample+' + new Date().getTime() + '@example.com',
    country: 'Japan',
    language: 'ja',
    source: TGI.Enums.SOURCE.SYSTEM,
    notes: 'Generated by the installation smoke test.'
  });

  SpreadsheetApp.getUi().alert(
    TGI.APP_NAME,
    'Created guest: ' + guest.guest_id,
    SpreadsheetApp.getUi().ButtonSet.OK
  );
  return guest;
}